language: haxe

# TravisCI by default run on linux.
# Let's enable both linux and mac builds because why not?
os:
  - linux
  - osx

# Let's use OSX 10.10, which is the oldest version that homebrew provides bottles for.
# https://docs.travis-ci.com/user/osx-ci-environment/
osx_image: xcode6.4

# Let's use Ubuntu Trusty instead of Precise.
dist: trusty

# Test with Haxe 3.4.2 and Haxe development.
haxe:
  - "3.4.4"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # C++ (for rebuilding hxcpp)
      - gcc-multilib
      - g++-multilib
      # Python
      - python3
      # PHP
      - php5-cli
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libglib2.0
      - libfreetype6

install:
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew uninstall --force brew-cask;
      brew update;
      brew install mono;
      brew install phantomjs;
      brew install python3;
    fi
  # Download and setup a standalone flash player debugger
  - haxe dev/flash/install.hxml
  # Install haxelibs
  - if [ "${TRAVIS_HAXE_VERSION}" = "development" ]; then
      haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git;
      pushd $(haxelib path hxcpp | head -1);
        pushd tools/hxcpp; haxe compile.hxml; popd;
        pushd project; neko build.n; popd;
      popd;
    else
      haxelib install hxcpp;
    fi
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib install utest
  - haxelib list

script:
  - haxe dev/ci/build-interp.hxml
  - haxe dev/ci/build-neko.hxml         && neko bin/neko/TestMainHx.n
  - haxe dev/ci/build-js.hxml           && node bin/js/TestMainHx.js
                                        && haxe dev/phantomjs/run.hxml bin/js/TestMainHx.js
  - haxe dev/ci/build-java.hxml         && java -jar bin/java/TestMainHx.jar
  - haxe dev/ci/build-php.hxml          && php bin/php/index.php
# Avoid php7 (fails on travis)  - haxe dev/ci/build-php7.hxml         && php bin/php7/index.php
  - haxe dev/ci/build-cs.hxml           && mono bin/cs/bin/TestMainHx.exe
  - haxe dev/ci/build-flash.hxml -D fdb && haxe dev/flash/run.hxml bin/flash/TestMainHx.swf
  - haxe dev/ci/build-cpp.hxml          && ./bin/cpp/TestMainHx
  - haxe dev/ci/build-python.hxml       && python3 bin/python/TestMainHx.py