version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 3.4.4 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install test dependencies
  - cinst phantomjs -y
  # Install php
  # http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst php -y
  - RefreshEnv
  # Download and setup a standalone flash player debugger
  - haxe dev/flash/install.hxml
  # Install project dependencies
  # `> log.txt || type log.txt` is for muting the output unless there is an error
  - haxelib install hxcpp  > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hxjava > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hxcs   > log.txt || type log.txt && cmd /C exit 1
  - haxelib install utest  > log.txt || type log.txt && cmd /C exit 1
  - haxelib list

# We don't use the build section, but do both build and 
# test in `test_script:`.
# It is just because it is more similar to the TravisCI config,
# thus it would be easier to update both of them.
build: off

test_script:
  - haxe dev/ci/build-interp.hxml
  - haxe dev/ci/build-neko.hxml         && neko bin\neko\TestMainHx.n
  - haxe dev/ci/build-js.hxml           && node bin\js\TestMainHx.js
                                        && haxe dev\phantomjs\run.hxml bin\js\TestMainHx.js
  - haxe dev/ci/build-java.hxml         && java -jar bin\java\TestMainHx.jar
  - haxe dev/ci/build-php.hxml          && php bin\php\index.php
  - haxe dev/ci/build-php7.hxml         && php bin\php7\index.php
  - haxe dev/ci/build-cs.hxml           && bin\cs\bin\TestMainHx.exe
  - haxe dev/ci/build-flash.hxml -D fdb && haxe dev\flash\run.hxml bin\flash\TestMainHx.swf
  - haxe dev/ci/build-cpp.hxml          && bin\cpp\TestMainHx.exe
  - haxe dev/ci/build-python.hxml       && C:\Python34-x64\python.exe bin\python\TestMainHx.py